import "../styles/globals.css"
import CssBaseline from "@mui/material/CssBaseline"
import { lightTheme } from "@/themes/light-theme";
import { ThemeProvider } from "@mui/material";
import ThemeRegistry from "@/themes/ThemeRegistry";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <CssBaseline />
      <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
      {/* {children} */}
      </body>
    </html>
  )
}
