import "../styles/globals.css"
import CssBaseline from "@mui/material/CssBaseline"
import Providers from "@/providers/Providers";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <Providers>
          <Navbar/>
          {children}
        </Providers>
        {/* {children} */}
      </body>
    </html>
  )
}
